# Changes here will be overwritten by Copier
_commit: v2.0.1
_src_path: gh:lincc-frameworks/python-project-template
author_email: name@you.com
author_name: Olivia Lynn
create_example_module: true
custom_install: true
enforce_style:
- pylint
- black
- isort
failure_notification: []
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: zendono_demo
project_license: MIT
project_name: zendono_demo
project_organization: OliviaLynn
python_versions:
- '3.9'
- '3.10'
- '3.11'
